### PR TITLE
open applications for 2020 seminar

### PR DESCRIPTION
**Pull request by adamjonas**

### CODE REVIEW

**Comment by adamjonas** [comment]
preview at: https://5e4469a7e1470900081dd9fe--chaincoderesidency.netlify.com/

**Comment by Caralie** [comment]
Looks great, thanks Jonas - 

This paragraph is a little bulky:
If you have wanted to contribute to open-source Bitcoin protocol projects but found the idea daunting, or want to spend more time designing protocols based on Bitcoin and Lightning, thinking about edge cases and security models with established protocol developers, this is an excellent opportunity.

Suggestion:
This is an excellent opportunity if you want to 
- contribute to open-source Bitcoin protocol projects but find the idea daunting,
- spend more time designing protocols based on Bitcoin and Lightning, 
- think about edge cases and security models with established protocol developers

**Comment by adamjonas** [comment]
@Caralie preview after commit f366cf8

**Comment by adamjonas** [comment]
now with resources page: https://5e46c763affcf700089de659--chaincoderesidency.netlify.com/

**Comment by jnewbery** [comment]
The preview looks good, but I don't get the same if I try to serve it locally. Is netlify regenerating the min.css file? I've tried doing that with gulp, but some of the css breaks.

**Comment by adamjonas** [comment]
@jnewbery a231786f7c3af206e155f1291af713de59e69790 should do it. Build with 'gulp dev'.

**Comment by jnewbery** [comment]
ACK

**Pull request merged**
